# ========================================
# CONFIGURAÇÃO PARA CONSOLE AWS AMPLIFY
# ========================================
# 
# INSTRUÇÕES:
# 1. Acesse: AWS Console > Amplify > d31iho7gw23enq
# 2. Menu: "Configurações de compilação" (Build settings)
# 3. APAGUE todo conteúdo do editor
# 4. COLE o código abaixo
# 5. Clique em "Salvar"
# 6. Clique em "Reimplantar esta versão"
#
# ========================================

version: 1
frontend:
  phases:
    preBuild:
      commands:
        - git clone https://github.com/flutter/flutter.git -b 3.32.4 --depth 1
        - export PATH="$PATH:`pwd`/flutter/bin"
        - flutter --version
        - flutter pub get
    build:
      commands:
        - flutter build web --release
  artifacts:
    baseDirectory: build/web
    files:
      - '**/*'
  cache:
    paths:
      - /root/.pub-cache/**/*
      - flutter/**/*