# ========================================
# CONFIGURAÇÃO PARA CONSOLE AWS AMPLIFY
# ========================================
# 
# INSTRUÇÕES:
# 1. Acesse: AWS Console > Amplify > d31iho7gw23enq
# 2. Menu: "Configurações de compilação" (Build settings)
# 3. APAGUE todo conteúdo do editor
# 4. COLE o código abaixo
# 5. Clique em "Salvar"
# 6. Clique em "Reimplantar esta versão"
#
# ========================================

version: 1
frontend:
  phases:
    preBuild:
      commands:
        - rm -rf flutter
        - wget -O flutter.tar.xz https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.22.1-stable.tar.xz
        - tar xf flutter.tar.xz
        - export PATH="$PATH:`pwd`/flutter/bin"
        - flutter doctor
        - flutter pub get
    build:
      commands:
        - export PATH="$PATH:`pwd`/flutter/bin"
        - flutter build web --release
  artifacts:
    baseDirectory: build/web
    files:
      - '**/*'
  cache:
    paths:
      - /root/.pub-cache/**/*
      - flutter.tar.xz