coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 5%
    patch:
      default:
        target: 80%

ignore:
  - "lib/generated_plugin_registrant.dart"
  - "lib/**/*.g.dart"
  - "lib/**/*.freezed.dart"
  - "test/**/*"