// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_application_1/test/features/appointments/application/appointment_providers_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flutter_application_1/core/models/appointment_model.dart'
    as _i2;
import 'package:flutter_application_1/features/appointments/services/appointments_service_v2.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAppointment_0 extends _i1.SmartFake implements _i2.Appointment {
  _FakeAppointment_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AppointmentsServiceV2].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppointmentsServiceV2 extends _i1.Mock
    implements _i3.AppointmentsServiceV2 {
  MockAppointmentsServiceV2() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Appointment> createAppointment({
    required String? professionalId,
    required String? serviceId,
    required DateTime? appointmentDateTime,
    required String? clientName,
    required String? clientPhone,
    required String? service,
    required double? price,
    String? notes,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createAppointment, [], {
              #professionalId: professionalId,
              #serviceId: serviceId,
              #appointmentDateTime: appointmentDateTime,
              #clientName: clientName,
              #clientPhone: clientPhone,
              #service: service,
              #price: price,
              #notes: notes,
            }),
            returnValue: _i4.Future<_i2.Appointment>.value(
              _FakeAppointment_0(
                this,
                Invocation.method(#createAppointment, [], {
                  #professionalId: professionalId,
                  #serviceId: serviceId,
                  #appointmentDateTime: appointmentDateTime,
                  #clientName: clientName,
                  #clientPhone: clientPhone,
                  #service: service,
                  #price: price,
                  #notes: notes,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.Appointment>);

  @override
  _i4.Future<List<_i2.Appointment>> getAppointments({String? status}) =>
      (super.noSuchMethod(
            Invocation.method(#getAppointments, [], {#status: status}),
            returnValue: _i4.Future<List<_i2.Appointment>>.value(
              <_i2.Appointment>[],
            ),
          )
          as _i4.Future<List<_i2.Appointment>>);

  @override
  _i4.Future<_i2.Appointment> updateAppointmentStatus(
    String? appointmentId,
    _i2.AppointmentStatus? newStatus,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateAppointmentStatus, [
              appointmentId,
              newStatus,
            ]),
            returnValue: _i4.Future<_i2.Appointment>.value(
              _FakeAppointment_0(
                this,
                Invocation.method(#updateAppointmentStatus, [
                  appointmentId,
                  newStatus,
                ]),
              ),
            ),
          )
          as _i4.Future<_i2.Appointment>);

  @override
  _i4.Future<List<_i2.Appointment>> getAppointmentsList({String? status}) =>
      (super.noSuchMethod(
            Invocation.method(#getAppointmentsList, [], {#status: status}),
            returnValue: _i4.Future<List<_i2.Appointment>>.value(
              <_i2.Appointment>[],
            ),
          )
          as _i4.Future<List<_i2.Appointment>>);

  @override
  _i4.Future<_i2.Appointment> updateAppointment(_i2.Appointment? appointment) =>
      (super.noSuchMethod(
            Invocation.method(#updateAppointment, [appointment]),
            returnValue: _i4.Future<_i2.Appointment>.value(
              _FakeAppointment_0(
                this,
                Invocation.method(#updateAppointment, [appointment]),
              ),
            ),
          )
          as _i4.Future<_i2.Appointment>);

  @override
  _i4.Future<void> deleteAppointment(String? appointmentId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAppointment, [appointmentId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i2.Appointment>> createBatchAppointments(
    List<_i2.Appointment>? appointments,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createBatchAppointments, [appointments]),
            returnValue: _i4.Future<List<_i2.Appointment>>.value(
              <_i2.Appointment>[],
            ),
          )
          as _i4.Future<List<_i2.Appointment>>);

  @override
  _i4.Future<List<_i2.Appointment>> updateBatchStatus(
    List<String>? ids,
    _i2.AppointmentStatus? status,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateBatchStatus, [ids, status]),
            returnValue: _i4.Future<List<_i2.Appointment>>.value(
              <_i2.Appointment>[],
            ),
          )
          as _i4.Future<List<_i2.Appointment>>);

  @override
  _i4.Future<_i2.Appointment> updateClientConfirmation(
    String? id,
    bool? isConfirmed,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateClientConfirmation, [id, isConfirmed]),
            returnValue: _i4.Future<_i2.Appointment>.value(
              _FakeAppointment_0(
                this,
                Invocation.method(#updateClientConfirmation, [id, isConfirmed]),
              ),
            ),
          )
          as _i4.Future<_i2.Appointment>);
}
