version = 0.1

[default]
[default.global.parameters]
stack_name = "agenda-facil-dev"
resolve_s3 = true
s3_prefix = "agenda-facil-dev"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []

[default.build.parameters]
cached = true
parallel = true

[default.deploy.parameters]
confirm_changeset = false
fail_on_empty_changeset = false
parameter_overrides = "Environment=dev CognitoDomainPrefix=agenda-facil-dev"

[dev]
[dev.deploy.parameters]
stack_name = "agenda-facil-dev-new"
s3_prefix = "agenda-facil-dev-new"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=dev CognitoDomainPrefix=agenda-facil-dev"
confirm_changeset = false
fail_on_empty_changeset = false
resolve_s3 = true

[prod]
[prod.deploy.parameters]
stack_name = "agenda-facil-prod"
s3_prefix = "agenda-facil-prod"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=prod CognitoDomainPrefix=agenda-facil-prod"
confirm_changeset = true
fail_on_empty_changeset = false