AWSTemplateFormatVersion: '2010-09-09'
Description: 'Infraestrutura AWS para App de Agendamentos'

Parameters:
  AppName:
    Type: String
    Default: 'agendamentos-app'

Resources:
  # Cognito User Pool
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub '${AppName}-user-pool'
      AutoVerifiedAttributes:
        - email
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireUppercase: true
          RequireLowercase: true
          RequireNumbers: true

  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref UserPool
      ClientName: !Sub '${AppName}-client'
      GenerateSecret: false
      ExplicitAuthFlows:
        - ADMIN_NO_SRP_AUTH
        - USER_PASSWORD_AUTH

  # DynamoDB Tables
  AgendamentosTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${AppName}-agendamentos'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH

Outputs:
  UserPoolId:
    Description: 'Cognito User Pool ID'
    Value: !Ref UserPool
    Export:
      Name: !Sub '${AppName}-UserPoolId'

  UserPoolClientId:
    Description: 'Cognito User Pool Client ID'
    Value: !Ref UserPoolClient
    Export:
      Name: !Sub '${AppName}-UserPoolClientId'

  AgendamentosTableName:
    Description: 'DynamoDB Table Name'
    Value: !Ref AgendamentosTable
    Export:
      Name: !Sub '${AppName}-TableName'