AWSTemplateFormatVersion: '2010-09-09'
Description: 'AGENDEMAIS - Monitoring and Alerts'

Parameters:
  EmailAddress:
    Type: String
    Description: Email for alerts
    Default: admin@agendemais.com

Resources:
  AlertTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: agendemais-alerts
      Subscription:
        - Protocol: email
          Endpoint: !Ref EmailAddress

  LambdaErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: agendemais-lambda-errors
      AlarmDescription: Lambda function errors
      MetricName: Errors
      Namespace: AWS/Lambda
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      AlarmActions:
        - !Ref AlertTopic

  DynamoDBThrottleAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: agendemais-dynamodb-throttles
      AlarmDescription: DynamoDB throttling
      MetricName: ThrottledRequests
      Namespace: AWS/DynamoDB
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      AlarmActions:
        - !Ref AlertTopic

  Dashboard:
    Type: AWS::CloudWatch::Dashboard
    Properties:
      DashboardName: AGENDEMAIS-Metrics
      DashboardBody: !Sub |
        {
          "widgets": [
            {
              "type": "metric",
              "properties": {
                "metrics": [
                  ["AWS/Lambda", "Invocations", "FunctionName", "agendemais-backend-AuthFunction"],
                  [".", "Errors", ".", "."],
                  [".", "Duration", ".", "."]
                ],
                "period": 300,
                "stat": "Sum",
                "region": "us-east-1",
                "title": "Lambda Metrics"
              }
            }
          ]
        }