AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudWatch Alarms for AgendaFácil SaaS'

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - staging
      - prod
    Description: Environment name
    
  ApiGatewayName:
    Type: String
    Default: agenda-facil-api
    Description: Name of the API Gateway
    
  LambdaFunctionPrefix:
    Type: String
    Default: agenda-facil
    Description: Prefix for Lambda functions
    
  DynamoDBTableName:
    Type: String
    Default: AgendaFacilTable
    Description: Name of the DynamoDB table
    
  NotificationEmail:
    Type: String
    Default: alerts@agendafacil.com
    Description: Email address for notifications
    
  SlackWebhookURL:
    Type: String
    Default: ''
    Description: Slack webhook URL for notifications
    NoEcho: true

Resources:
  # SNS Topic for alerts
  AlertTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: !Sub 'AgendaFacil-${Environment}-Alerts'
      TopicName: !Sub 'AgendaFacil-${Environment}-Alerts'
      
  EmailSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: email
      Endpoint: !Ref NotificationEmail
      TopicArn: !Ref AlertTopic
      
  # Lambda Error Rate Alarm
  LambdaErrorRateAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${Environment}-LambdaErrorRate'
      AlarmDescription: 'Alarm when Lambda error rate exceeds threshold'
      MetricName: Errors
      Namespace: AWS/Lambda
      Statistic: Sum
      Period: 60
      EvaluationPeriods: 2
      Threshold: 5
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: notBreaching
      Dimensions:
        - Name: FunctionName
          Value: !Sub '${LambdaFunctionPrefix}-${Environment}-AuthFunction'
      AlarmActions:
        - !Ref AlertTopic
      OKActions:
        - !Ref AlertTopic
        
  # Lambda Duration Alarm - Predictive
  LambdaDurationPredictiveAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${Environment}-LambdaDurationPredictive'
      AlarmDescription: 'Predictive alarm for Lambda duration anomalies'
      MetricName: Duration
      Namespace: AWS/Lambda
      Statistic: Average
      Period: 60
      EvaluationPeriods: 3
      Threshold: 3
      ComparisonOperator: GreaterThanUpperThreshold
      TreatMissingData: notBreaching
      Dimensions:
        - Name: FunctionName
          Value: !Sub '${LambdaFunctionPrefix}-${Environment}-AuthFunction'
      AlarmActions:
        - !Ref AlertTopic
      ThresholdMetricId: ad1
      Metrics:
        - Id: m1
          MetricStat:
            Metric:
              Namespace: AWS/Lambda
              MetricName: Duration
              Dimensions:
                - Name: FunctionName
                  Value: !Sub '${LambdaFunctionPrefix}-${Environment}-AuthFunction'
            Period: 60
            Stat: Average
            Unit: Milliseconds
        - Id: ad1
          Expression: 'ANOMALY_DETECTION_BAND(m1, 2)'
          Label: DurationAnomalyDetection
          
  # API Gateway 4xx Error Rate Alarm
  ApiGateway4xxErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${Environment}-ApiGateway4xxError'
      AlarmDescription: 'Alarm when 4xx error rate exceeds threshold'
      MetricName: 4XXError
      Namespace: AWS/ApiGateway
      Statistic: Sum
      Period: 60
      EvaluationPeriods: 2
      Threshold: 10
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: notBreaching
      Dimensions:
        - Name: ApiName
          Value: !Ref ApiGatewayName
      AlarmActions:
        - !Ref AlertTopic
        
  # API Gateway 5xx Error Rate Alarm
  ApiGateway5xxErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${Environment}-ApiGateway5xxError'
      AlarmDescription: 'Alarm when 5xx error rate exceeds threshold'
      MetricName: 5XXError
      Namespace: AWS/ApiGateway
      Statistic: Sum
      Period: 60
      EvaluationPeriods: 1
      Threshold: 5
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: notBreaching
      Dimensions:
        - Name: ApiName
          Value: !Ref ApiGatewayName
      AlarmActions:
        - !Ref AlertTopic
        
  # API Gateway Latency Alarm - Predictive
  ApiGatewayLatencyPredictiveAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${Environment}-ApiGatewayLatencyPredictive'
      AlarmDescription: 'Predictive alarm for API Gateway latency anomalies'
      MetricName: Latency
      Namespace: AWS/ApiGateway
      Statistic: p95
      Period: 60
      EvaluationPeriods: 3
      Threshold: 3
      ComparisonOperator: GreaterThanUpperThreshold
      TreatMissingData: notBreaching
      Dimensions:
        - Name: ApiName
          Value: !Ref ApiGatewayName
      AlarmActions:
        - !Ref AlertTopic
      ThresholdMetricId: ad1
      Metrics:
        - Id: m1
          MetricStat:
            Metric:
              Namespace: AWS/ApiGateway
              MetricName: Latency
              Dimensions:
                - Name: ApiName
                  Value: !Ref ApiGatewayName
            Period: 60
            Stat: p95
            Unit: Milliseconds
        - Id: ad1
          Expression: 'ANOMALY_DETECTION_BAND(m1, 2)'
          Label: LatencyAnomalyDetection
          
  # DynamoDB Throttled Requests Alarm
  DynamoDBThrottledRequestsAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${Environment}-DynamoDBThrottledRequests'
      AlarmDescription: 'Alarm when DynamoDB throttled requests exceed threshold'
      MetricName: ThrottledRequests
      Namespace: AWS/DynamoDB
      Statistic: Sum
      Period: 60
      EvaluationPeriods: 2
      Threshold: 10
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: notBreaching
      Dimensions:
        - Name: TableName
          Value: !Ref DynamoDBTableName
      AlarmActions:
        - !Ref AlertTopic
        
  # DynamoDB Read Capacity Utilization Alarm - Predictive
  DynamoDBReadCapacityPredictiveAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${Environment}-DynamoDBReadCapacityPredictive'
      AlarmDescription: 'Predictive alarm for DynamoDB read capacity utilization'
      MetricName: ConsumedReadCapacityUnits
      Namespace: AWS/DynamoDB
      Statistic: Sum
      Period: 60
      EvaluationPeriods: 3
      Threshold: 3
      ComparisonOperator: GreaterThanUpperThreshold
      TreatMissingData: notBreaching
      Dimensions:
        - Name: TableName
          Value: !Ref DynamoDBTableName
      AlarmActions:
        - !Ref AlertTopic
      ThresholdMetricId: ad1
      Metrics:
        - Id: m1
          MetricStat:
            Metric:
              Namespace: AWS/DynamoDB
              MetricName: ConsumedReadCapacityUnits
              Dimensions:
                - Name: TableName
                  Value: !Ref DynamoDBTableName
            Period: 60
            Stat: Sum
        - Id: ad1
          Expression: 'ANOMALY_DETECTION_BAND(m1, 2)'
          Label: ReadCapacityAnomalyDetection
          
  # DynamoDB Write Capacity Utilization Alarm - Predictive
  DynamoDBWriteCapacityPredictiveAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${Environment}-DynamoDBWriteCapacityPredictive'
      AlarmDescription: 'Predictive alarm for DynamoDB write capacity utilization'
      MetricName: ConsumedWriteCapacityUnits
      Namespace: AWS/DynamoDB
      Statistic: Sum
      Period: 60
      EvaluationPeriods: 3
      Threshold: 3
      ComparisonOperator: GreaterThanUpperThreshold
      TreatMissingData: notBreaching
      Dimensions:
        - Name: TableName
          Value: !Ref DynamoDBTableName
      AlarmActions:
        - !Ref AlertTopic
      ThresholdMetricId: ad1
      Metrics:
        - Id: m1
          MetricStat:
            Metric:
              Namespace: AWS/DynamoDB
              MetricName: ConsumedWriteCapacityUnits
              Dimensions:
                - Name: TableName
                  Value: !Ref DynamoDBTableName
            Period: 60
            Stat: Sum
        - Id: ad1
          Expression: 'ANOMALY_DETECTION_BAND(m1, 2)'
          Label: WriteCapacityAnomalyDetection

Outputs:
  AlertTopicArn:
    Description: ARN of the SNS topic for alerts
    Value: !Ref AlertTopic