name: Build Flutter Web & Deploy to Amplify

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.9'
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Build Web
        run: flutter build web --release --base-href=/

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy to Amplify
        run: |
          # Zip build files
          cd build/web
          zip -r ../../deploy.zip .
          cd ../..
          
          # Upload to S3 and trigger Amplify deployment
          aws s3 cp deploy.zip s3://amplify-agendafacil-build/
          aws amplify start-deployment \
            --app-id d31iho7gw23enq \
            --branch-name main \
            --source-url s3://amplify-agendafacil-build/deploy.zip

      - name: Notify Success
        run: |
          echo "✅ Flutter Web build completed successfully!"
          echo "🚀 Deployed to: https://main.d31iho7gw23enq.amplifyapp.com/"